spring.application.name=RevHire
server.port=9090

# Database Configuration
spring.datasource.url=jdbc:mysql://revhire.cbo8eqw840js.ap-south-2.rds.amazonaws.com:3306/revhire_db?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=Admin_12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Limits
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Thymeleaf
spring.thymeleaf.cache=false

# Mail (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=revhire.careers@gmail.com
spring.mail.password=tjapamgeokxiylgw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
#logging.level.org.springframework.mail=DEBUG
#logging.level.com.sun.mail=DEBUG



# Frontend URL for password reset links
app.frontend.url=${FRONTEND_URL:http://localhost:4200}
